//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KongreForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basvuru
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Basvuru()
        {
            this.BasvuruDetays = new HashSet<BasvuruDetay>();
            this.BasvuruEvraks = new HashSet<BasvuruEvrak>();
        }
    
        public int Id { get; set; }
        public int FKKisiId { get; set; }
        public int FKKongreId { get; set; }
        public Nullable<bool> Onay { get; set; }
        public Nullable<System.DateTime> OnayZaman { get; set; }
        public System.DateTime BasvuruZaman { get; set; }
        public string BasvuruKodu { get; set; }
        public Nullable<int> SunumTipi { get; set; }
        public Nullable<bool> SunucuMu { get; set; }
        public string Ozet { get; set; }
        public Nullable<bool> PosterMi { get; set; }
        public string Baslik { get; set; }
    
        public virtual Kisi Kisi { get; set; }
        public virtual Kongre Kongre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruDetay> BasvuruDetays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruEvrak> BasvuruEvraks { get; set; }
    }
}
