//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KongreForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasvuruDetay
    {
        public int Id { get; set; }
        public int FKOturumId { get; set; }
        public Nullable<int> FKKullaniciId { get; set; }
        public int FKBasvuruId { get; set; }
        public Nullable<System.DateTime> OnayZaman { get; set; }
        public Nullable<bool> Onay { get; set; }
    
        public virtual Basvuru Basvuru { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Oturum Oturum { get; set; }
    }
}
