//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KongreForm.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KongreDbEntities : DbContext
    {
        public KongreDbEntities()
            : base("name=KongreDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Basvuru> Basvurus { get; set; }
        public virtual DbSet<BasvuruDetay> BasvuruDetays { get; set; }
        public virtual DbSet<BasvuruEvrak> BasvuruEvraks { get; set; }
        public virtual DbSet<Kisi> Kisis { get; set; }
        public virtual DbSet<Kongre> Kongres { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<Oturum> Oturums { get; set; }
        public virtual DbSet<Yetki> Yetkis { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Aktif> Aktifs { get; set; }
    }
}
