//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KongreForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oturum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oturum()
        {
            this.BasvuruDetays = new HashSet<BasvuruDetay>();
        }
    
        public int Id { get; set; }
        public int FKKongreId { get; set; }
        public string OturumAd { get; set; }
        public System.DateTime OturumBaslangic { get; set; }
        public System.DateTime OturumBitis { get; set; }
        public bool IsChecked { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasvuruDetay> BasvuruDetays { get; set; }
        public virtual Kongre Kongre { get; set; }
    }
}
