//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KongreForm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yetki
    {
        public int Id { get; set; }
        public int FKKongreId { get; set; }
        public int FKKullaniciId { get; set; }
    
        public virtual Kongre Kongre { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
